name: CI

on:
  push:
    branches:
      - main  # Если пуш то в ветку main
  pull_request:
    branches:
      - main  # Если пул реквест то в ветке main

jobs:
  build:
    runs-on: windows-latest  # Использовать последнюю версию Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонировать репозиторий

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'  # Установить JDK 23
          distribution: 'adopt'
          
      - name: Directory Change
        run: cd demo
        
      - name: Maven Test
        run: mvn clean test  # Запуск теста

      - name: Generate Allure Report
        run: mvn allure:report  # Генерация отчета Allure

      - name: Allure Report on GitHub Pages
        run: |
          # Создаем новую ветку gh-pages
          git config --global user.name "Hirode"
          git config --global user.email "926695016@mail.ru"
          git checkout -b gh-pages
          # Копируем сгенерированный отчет в корень ветки
          cp -r target/site/allure-maven-plugin/* .
          # Добавляем и коммитим изменения
          git add .
          git commit -m "Deploy Allure report"
          # Пушим изменения в ветку gh-pages
          git push --force --set-upstream origin gh-pages
